# Configuración de la base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Cambiar la propiedad desactualizada a la nueva recomendada
spring.sql.init.platform=h2

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola de H2 para ver la base de datos en el navegador
spring.h2.console.enabled=true

# Configuración del puerto
server.port=8081